export default {
  researches: [
    {
      id: 1,
      title: "Augmented Reality with Fologram",
      type: "Advanced Productions",
      time: "Fall",
      year: "2019",
      shouldChangeColor: true, //Goes for the ones with white images in their case study section
      headerDescription:
        "Team Project with Shantanu Kushalappa and Daniel Oddo.",
      infoDescription:
        "The project was an interactive design and fabrication experiment with Fologram, a plugin for Rhino and Grasshopper.",
      detailsDescription1: `We created a digital base model in grasshopper/Rhino and used the Fologram for Hololense to map and directly fabricate it in space. Our
platform was a set of poles screwed to a wooden base. We used 1/8” steel rods to fabricate the loop geometries. Using the platform as a base, we
used Fologram to design on top of our physical model.`,
      detailsDescription3: `After welding all the connections, the model was removed from the base, painted and put
back on the base again. Also, we designed multiple digital information layers on top of the physical model which we could interact with through
the Fologram app for both our phones and the Hololens. `,
      images: {
        header: "/fologram/fologram-header.jpg",
        showcase: "/fologram/fologram-case.jpg",
        details1: "/fologram/fologram-details1.jpg",
        details2: "/fologram/fologram-details2.jpg",
        process: [
          "/fologram/fologram-process-1.jpg",
          "/fologram/fologram-process-2.jpg",
          "/fologram/fologram-process-3.jpg",
        ],
      },
    },
    {
      id: 2,
      title: "Woven Wall Panels",
      type: "Independent Study",
      time: "Fall",
      year: "2019",

      headerDescription:
        "The project is on bending active systems and torsion as a form driver in plate geometries.",
      infoDescription:
        "The study builds on principles from previous research on plate-bending-active tensile structures. ",

      images: {
        header: "/woven/woven-header.png",
        showcase: "/woven/woven-case.png",
        details1: "",
        details2: "",
        process: ["/woven/woven-process.png"],
      },
    },

    {
      id: 3,
      title: "Remote Sensing + Complex Geometry Foam Cutting",
      type: "Team Study",
      time: "Spring",
      year: "2019",
      shouldChangeColor: true, //Goes for the ones with white images in their case study section
      headerDescription: "Team Project with Mehmet Sinan Bermek.",
      infoDescription:
        "The project focuses on the feasibility of automated fabrication and assembly of complex geometries using computer vision and a KUKA robotic arm. ",

      detailsDescription1: `The project focuses on the feasibility of automated fabrication and assembly of complex
      geometries using computer vision and a KUKA robotic arm.
      The process consists of two parts:
      1- Parametric design and hot wire foam cutting of complex geometries using the KUKA.
      2- Probing the environment through a visible spectrum camera to correct or generate
      pick up and placement paths.`,
      detailsDescription3: `The project was done in a team of two. I was responsible for programming the robotic art
      to cut the geometries in foam with a hot wire. Grasshopper scripting was used to 1) design
      the geometry and shapes to be hotwired by the KUKA and 2) program the KUKA motions.
      The design goal was to achieve complex geometries by the application of simple cuts.
      The shapes were designed by generating parametric planes and trimming a cube against
      them. Each shape was generated by application of up to 3 straight and/or V cuts.`,

      images: {
        header: "/foamcutting/foamcutting-header.jpg",
        showcase: "/foamcutting/foamcutting-case.jpg",
        details1: "/foamcutting/foamcutting-details1.jpg",
        details2: "",
        process: ["/foamcutting/foamcutting-process.jpg"],
      },
    },
    {
      id: 4,
      title: "The Infinite Line Pavilion",
      image: "./capture.jpg",
      year: "2015",
    },
  ],
  designs: [
    {
      id: 5,
      title: "Urban Female Heterotopia",
      type: "M.Arch. Capstone Project",
      time: "Spring",
      year: "2017",

      headerDescription:
        "An architectural subversion of the genderbased segregation of public space in Tehran",
      infoDescription:
        "This project addresses the experiences of women in public space in Tehran, Iran by analyzing the spatial power dynamics in society and critiquing them in a radical fashion. ",

      detailsDescription1: `Along College Bridge to Valiasr Square there are several
      universities and cultural centers. Enghelab street is the book store
      district in the city. These locations attract a significant population
      of students and academics. It is, therefore, the starting point for
      many political and social protests. This attitude is reflected in
      cafes and other gathering spaces in the area. These spaces play
      the role of counter-spaces, and develop a culture of resistance
      to the power. The site is an old theatre --Cinema Enghelab-- on
      Enghelab street.`,

      detailsDescription2: `The site is chosen because it holds a memory specific to the area
        and is surrounded by spaces representing both sides of power:
        where segregation is intensified and where counter-spaces are
        developed.
        This segregation-power matrix was developed to analyze and
        identify methods and devices of spatial segregation through
        architecture. It was used to find the weak zones where the
        segregation line is not rigid. The matrix decodes power structures,
        hierarchy within each space, and the experience of users within
        them.`,
      detailsDescription3: `The design emphasizes experiences that exist in social space
      as a result of gendered power dynamics.
      From the outside, the building is a simple box, not revealing the
      interior scheme. This holds the memory of the theatre’s form,
      and emphasizes the concept of a heterotopia by hiding in plain
      sight.
      There is a line running throughout the building, separating
      spaces and emotions. It’s the extruded line of segregation
      in Iran that does not always have physical form. The design
      takes that line, twists it, breaks and manipulates it. The line is
      produced in conjunction with the program of each space. `,
      detailsDescription4: `Depending on whether the space is It takes the form of
      furniture, openings, corridors shelves and etc in the building. It
      does not touch the perimeter of the building. The space creates
      the feeling of being excluded, watched, oppressed or limited.
      Each space is tuned to demonstrate spatial power dynamics in
      order to make them obvious and indefensible. 
      Each program demonstrates segregation in a different way. The book store divides books by stereotypical gendered readership while breaking the lines between the shelves. Similarly, the gallery divides spaces into those dedicated to male and female artists. Cafes and game cafes unify or divide users, and other uses, like the socializing and lobby spaces, make use of sight and vantage to create power dynamics in the space. The space stretches out to the rooftop, where only pieces of the line remain.
      `,

      images: {
        header: "/capstone/heterotopia-header.jpg",
        showcase: "/capstone/heterotopia-case.png",
        details1: "/capstone/heterotopia-details1.jpg",
        details2: "/capstone/heterotopia-details2.jpg",
        process: [
          "/capstone/heterotopia-process-1.jpg",
          "/capstone/heterotopia-process-2.jpg",
          "/capstone/heterotopia-process-3.jpg",
        ],
      },
    },
    { id: 1, title: "Terrace Apartment", image: "./main.jpg", year: "2021" },
    {
      id: 6,
      title: "Woven Wall Panels",
      image: "./capture-2.jpg",
      year: "20",
    },
    { id: 3, title: "Al-Bahr Towers", image: "./main.jpg", year: "2018" },
    {
      id: 7,
      title: "The Infinite Line Pavilion",
      image: "./capture.jpg",
      year: "2019",
    },
  ],
  academics: [
    {
      id: "I",
      title: "Carnegie Mellon University",
      degree: "PhD - Building Performance & Diagnostics",
      year: "2020 - 2023",
      image: "carnegiemellon.png",
    },
    {
      id: "II",
      title: "Georgia Institute of Technology",
      degree: "M.S - School of Architecture",
      year: "2019 - 2020",
      image: "georgiatech.png",
    },
    {
      id: "III",
      title: "Pennsylvania State University",
      degree: "M.Arch - Stuckeman School of Architecture and Landscape",
      year: "2014 - 2017",
      image: "pennstate.png",
    },
    {
      id: "IV",
      title: "Azad University West Tehran Branch",
      degree: "B.Arch - Department of Architecture",
      year: "2009 - 2014",
      image: "azad.png",
    },
  ],
};
